<html>
<head>
  <title>${cfg.title} | By: ${cfg.runBy} / ${printer.print(cfg.runAt)} </title>
  <style>
a,abbr,acronym,address,applet,article,aside,audio,
b,blockquote,big,body,
center,canvas,caption,cite,code,command,datalist,
dd,del,details,dfn,dl,div,dt,
em,embed,fieldset,figcaption,figure,font,footer,form,
h1,h2,h3,h4,h5,h6,header,hgroup,html,i,iframe,img,ins,
kbd,keygen,label,legend,li,meter,nav,object,ol,output,p,pre,progress,q,s,
samp,section,small,span,source,strike,strong,sub,sup,
table,tbody,tfoot,thead,th,tr,tdvideo,tt,u,ul,var{
	background:transparent;
	border:0 none;
	font-size:100%;
	margin:0;
	padding:0;
	border:0;
	outline:0;
	vertical-align:top
}
ul{
	list-style:none
}
blockquote,q{
	quotes:none
}
table,table td{
	padding:0;
	border:none;
	border-collapse:collapse
}
img{
	vertical-align:top
}
embed{
	vertical-align:top
}
article,aside,audio,canvas,command,datalist,details,embed,figcaption,figure,footer,header,hgroup,keygen,meter,nav,output,progress,section,source,video{display:block}
mark,rp,rt,ruby,summary,time{
	display:inline
}

body{
	font-family: Arial, Helvetica, sans-serif;
	line-height:1.4em;
	font-size:0.9em;
    background:url(../images/header-bg2.png) top repeat-x #fff;
	color:#555;
}
h1,h2,h3,h4,h5 {
	color:#333;
}
h1 {
   font-size:24px;
}
.col-header {
	font-weight: bold;
	border-bottom: 1px solid #333;
	padding: 3;
}
.col-data {
	border-bottom: 1px dashed #333;
	padding: 2;
}
  </style>
</head>
<body>

<table width="<#if cfg.orientation == "landscape">980<#else>660</#if>" style="margin:20px;">
<tr>
	<td style="width:100%">
		<table style="width:100%">
			   <tr>
			       <td><#if cfg.logo?has_content> <img src="${cfg.logo}"> </#if></td>
			       <td><h1>${cfg.title}</h1></td>
			       <td align=right>
				   	   User: ${cfg.runBy }  <br>
					   Date: ${printer.print(cfg.runAt)}
				   </td>
			   </tr>
		</table>
	</td>
</tr>
<tr>
	<td >
		<hr width="100%" size=1>
	</td>
</tr>
<tr>
	<td>
		<table style="width:100%">
		  <tr>
		  <#list colTitles as t>
		     <td class="col-header">${t} </td>
		  </#list>
		  </tr>

		  <#list data as m>
		  	<tr>
		    <#list colNames as c>
				<td class="col-data"><#if m[c]?has_content> ${printer.print(m[c])} </#if></td>
			</#list>
			</tr>
		</#list>
		</table>
	</td>
</tr>
<tr>
	<td >
		<hr width="100%" size=1>
	</td>
</tr>
<tr>
	<td style="width:100%">
		<table style="width:100%">
			   <tr>
			       <td style="font-size:12px;"> &copy; Nan21 Electronics  </td>
			       <td></td>
			       <td align=right style="font-size:10px;">
                        Generated by
				   				 Dnet eBusiness Suite.
				   </td>
			   </tr>
		</table>
	</td>
</tr>

</table>
</body>
</html>